# Generated by Django 3.0.5 on 2020-05-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_title', models.CharField(max_length=100)),
                ('file_type', models.CharField(max_length=50)),
                ('file_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_list', models.IntegerField(db_index=True)),
                ('song_title', models.CharField(max_length=50)),
                ('singer', models.CharField(max_length=50)),
                ('data_add_song', models.DateField(auto_now_add=True)),
                ('note_song', models.CharField(max_length=50)),
                ('file_sources', models.ManyToManyField(to='tool.FileSource')),
            ],
        ),
        migrations.CreateModel(
            name='SongList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_list_name', models.CharField(max_length=100)),
                ('data_add_list', models.DateField(auto_now_add=True)),
                ('note_list', models.CharField(max_length=50)),
                ('songs', models.ManyToManyField(to='tool.Song')),
            ],
        ),
        migrations.CreateModel(
            name='SongLibrary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('song_lists', models.ManyToManyField(null=True, to='tool.SongList')),
            ],
        ),
    ]
