# Generated by Django 3.0.5 on 2020-05-03 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='song',
            name='file_sources',
        ),
        migrations.DeleteModel(
            name='FileSource',
        ),
        migrations.AddField(
            model_name='song',
            name='urls',
            field=models.ManyToManyField(to='tool.Url'),
        ),
    ]
