# Generated by Django 3.0.5 on 2020-05-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0002_auto_20200503_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='urls',
        ),
        migrations.AddField(
            model_name='song',
            name='url1',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='url2',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='url3',
            field=models.URLField(null=True),
        ),
        migrations.DeleteModel(
            name='Url',
        ),
    ]
